baseurl = "https://heatherlent.co/blog/"
title = "Heather Lent's Blog"
theme = "pickles"
languageCode = "en-us"
copyright = "&copy; Heather Lent 2018"
paginate = 5
paginatePath = "page"

[Author]
    name = "Heather"
    profile = "https://heatherlent.co"

[Taxonomies]
    tag = "tags"

[Params]
    headline = "Heather Lent's Blog"
    description = "Heather Lent's technology blog, covering natural language processing, machine learning, and other data science topics."
    subtitle = "Heather Lent's technology blog, covering natural language processing, machine learning, and other data science topics."
    logo = "/favicon.png"
    favicon = "/favicon.png"
    github = "hclent"
    twitter = "heather_nlp"
    # ga_api_key = "UA-40399378-2"
    avatar = "https://heatherlent.co/assets/images/heather-portrait.jpg"
    author = "Heather Lent"
    authorwebsite = "http://heatherlent.co"
    bio = "NLP Engineer in Salt Lake City"
    contact = "mailto:hclent1@gmail.com"
    linkedin = "heather-lent-148307116"

[Permalinks]
    posts = "/:filename/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Website"
    url = "https://heatherlent.co/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "https://heatherlent.co/#about"
    weight = 4
